app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('food/',food,name='food'),
    path('drinks/',drinks,name='drinks'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('clothes/',clothes,name='clothes'),
    path('shoes/',shoes,name='shoes'),
]

project18/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def food(request):
    return render(request,'food.html')
def drinks(request):
    return render(request,'drinks.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def clothes(request):
    return render(request,'clothes.html')
def shoes(request):
    return render(request,'shoes.html')

templates/clothes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>Kurta is looking beautiful</h1>
        <img src="{% static 'images/kurta.jpg' %}" alt="No Image" height="300px" width="300px">
        <img src="{% static 'images/jeans.jpg' %}" alt="No Image" height="300px" width="300px">
        <h1><a href="{% url 'app1:drinks' %}">Back to drinks</a></h1>
        <h1><a href="{% url 'app1:food' %}">Back to food</a></h1>
        <h1><a href="{% url 'app2:shoes' %}">Back to shoes</a></h1>
    </center>
</body>
</html>

templates/drinks.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>Minute-milad is my favourite drink</h1>
        <img src="{% static 'images/wm.jpg' %}" alt="No Image" height="300px" width="300px">
        <img src="{% static 'images/orange.jpg' %}" alt="No Image" height="300px" width="300px">
        <h1><a href="{% url 'app1:food' %}">Back to food</a></h1>
        <h1><a href="{% url 'app2:clothes' %}">Back to clothes</a></h1>
        <h1><a href="{% url 'app2:shoes' %}">Back to shoes</a></h1>
    </center>
</body>
</html>

templates/food.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>Biryani is my favourite food</h1>
        <img src="{% static 'images/chicken.jpg' %}" alt="No Image" height="300px" width="300px">
        <img src="{% static 'images/egg.jpg' %}" alt="No Image" height="300px" width="300px">
        <h1><a href="{% url 'app1:drinks' %}">Back to drinks</a></h1>
        <h1><a href="{% url 'app2:clothes' %}">Back to clothes</a></h1>
        <h1><a href="{% url 'app2:shoes' %}">Back to drinks</a></h1>
    </center>
</body>
</html>

templates/shoes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>Snickers is a very comfortable to wear</h1>
        <img src="{% static 'images/shoes.jpg' %}" alt="No Image" height="300px" width="300px">
        <img src="{% static 'images/shoewomwn.jpg' %}" alt="No Image" height="300px" width="300px">
        <h1><a href="{% url 'app1:drinks' %}">Back to drinks</a></h1>
        <h1><a href="{% url 'app1:food' %}">Back to food</a></h1>
        <h1><a href="{% url 'app2:clothes' %}">Back to clothes</a></h1>
    </center>
</body>
</html>